package com.appinsnap.aishrm.util
import com.appinsnap.aishrm.BuildConfig

class Constants {
    companion object {
        const val BASE_URL_AIS = BuildConfig.SERVER_URL
        const val LEAVES_DETAIL_API = "SmartDash/GetLeaveDetails"
        const val Login_API = "Authentication/Login"
        const val NotificatioCount_API = "Authentication/GetNotificationsCount"
        const val WeeklyAttendance_API = "Authentication/GetWeekAttendance"
        const val DownloadAttendance_API = "SmartDash/DownloadAttendance"
        const val DownloadGraphData = "SmartDash/DownloadGraphData"
        const val CancelRequest_API = "SmartDash/rejectpendingrequest"
        const val ForgotPassword_API = "Authentication/ForgetPassword"
        const val OTP_API = "Authentication/ValidateOTP"
        const val categories="Categories"
        const val latesittingnotifid="notifiationid"
        const val latesittingcheckin = "Authentication/Latesittingcheckin"

        const val LateSittingDetail_API = "Authentication/latesitttingdetail"
        const val LateSittingDetailsSubmitt_API = "Authentication/AddLatesitting"
        const val isLateSittingEnableAPI = "Authentication/IsLateSetting "
        const val HISTORY_API = "Authentication/GetHistoryData"
        const val Logout_API = "Authentication/Logout"
        const val PasswordUpdate_API = "Authentication/UpdatePassword"
        const val Dashboard_API = "Authentication/GetDashboardData"
        const val AttendanceHistory_API = "Authentication/GetAttendanceHistory"
        const val Notifications_API = "Authentication/GetNotificationsv1"
        const val Approval_API = "Authentication/UpdateApprovalStatus"
        const val empname = "empname"
        const val isPMObit = "inPMObit"
        const val approvallayout = "approvallayout"
        const val checkindate = "checkindate"
        const val islogin = "islogin"
        var isListSorted:Boolean = true
        const val empid = "empid"
        const val latitude = "latitude"
        const val longitude = "longitude"
        const val employeeLoc = "emplpoyeeloc"
        const val status = "status"
        const val noOfDays = "noOfDays"
        const val departmentId = "departmentId"
        const val OFFICE_LOCATIONS = "officelocations"
        const val Leaves_data = "leavedata"
        const val LAST_LOCATIONS = "lastlocation"
        const val NotificationView_API = "Authentication/NotificationsViewed"
        const val REQUESTATTENDANCE_API = "Authentication/SubmitRequestResubmission"
        const val NEWS_API = "Authentication/GetEventsNews"
        const val AcceptRejectAPI = "Authentication/AcceptRejectAllRequests"
        const val CTOManagerEmployee_API = "SmartDash/CTOAndManagerViewEmployeDeatails"
        const val CTOManagerDashboardView = "SmartDash/CTOAndManagerView"
        const val GET_Policies_SOP = "Authentication/GetPolicies"
        const val selectedTab = "selectedTab"
        const val latesitting = "latesitting"
        const val viewid = "viewid"
        const val attendanceStatus = "attendanceStatus"
        const val checkinTime = "checkintime"
        const val characterlimit = "characterLimit"
        const val checkouttime = "checkoutTime"
        const val memberCount = "memberCount"
        const val profileurl = "profileurl"
        const val reportingto = "reportingto"
        const val department = "department"
        const val designation = "designation"
        const val cellno = "cellno"
        const val LEAVE_REQUEST ="Authentication/SubmitLeaveRequest"
        const val Attendance_API = "Authentication/AddAttendance"
        const val SETTING_API = "Authentication/SettingApi"
        const val GET_GRAPH_FILTERS = "SmartDash/DynamicFilteration"
        const val GET_DASHBOARD_STATICS_GRAPH = "SmartDash/CTOAndManagerViewSummry"
        const val GET_DASHBOARD_ATTENDANCE_GRAPH = "SmartDash/CTOAndManagerViewAttendanceSummry"
        const val UpdateLateSittingDetails = "Authentication/UpdateLatesittingbyPMO"
        var email = "email"
        var lastTimeClicked: Long = 0
        var SELECTEDdpt=0
        var DOWNLOAD_MSG="A new version is now available, please update to latest version by tapping on Update"
        var DOWNLOAD_APK_UAT="https://qa-aishrms.appinsnap.com/hrmswebapp/api/Download/AndroidDownloadfile"
        var DOWNLOAD_APK_QA="https://qa-aishrms.appinsnap.com/hrmswebapp/api/Download/AndroidDownloadfile"
        var DOWNLOAD_APK_PRE="https://uat-aishrms.appinsnap.com/hrmswebapp/api/Download/AndroidDownloadfile"
        var DOWNLOAD_APK_LIVE="https://hrms.appinsnap.com/api/api/Download/AndroidDownloadfile"
        var IS_MAIN_OPEN=false
        var IS_DIALOG_SHOWING=false
        @JvmField var graphViewMaker:String=""
    }

}
